/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    collections: Collection;
    books: Book;
    highlight: Highlight;
    orders: Order;
    'promo-codes': PromoCode;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    highlight: HighlightSelect<false> | HighlightSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'promo-codes': PromoCodesSelect<false> | PromoCodesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'reglages-boutique': ReglagesBoutique;
    'pages-legales': PagesLegales;
    'reglages-site': ReglagesSite;
    'page-a-propos': PageAPropos;
  };
  globalsSelect: {
    'reglages-boutique': ReglagesBoutiqueSelect<false> | ReglagesBoutiqueSelect<true>;
    'pages-legales': PagesLegalesSelect<false> | PagesLegalesSelect<true>;
    'reglages-site': ReglagesSiteSelect<false> | ReglagesSiteSelect<true>;
    'page-a-propos': PageAProposSelect<false> | PageAProposSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * Clé d'idempotence de la migration
   */
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Forme « Prénom Nom »
   */
  name: string;
  slug: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  name: string;
  slug: string;
  edition: 'editions-sociales' | 'la-dispute';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title: string;
  /**
   * Identifiant d'URL — ne pas modifier après publication
   */
  slug: string;
  edition?: ('editions-sociales' | 'la-dispute') | null;
  origin: 'catalogue' | 'boutique';
  presentation: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  presentationLegacyHtml?: string | null;
  plusLoin?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  plusLoinLegacyHtml?: string | null;
  contentTouched?: boolean | null;
  isbn?: string | null;
  /**
   * Prix TTC — la TVA 5,5 % est incluse et jamais recalculée au checkout (pratique actuelle conservée, plan phase 4 étape 8).
   */
  prix?: number | null;
  pages?: number | null;
  dateParution: string;
  /**
   * Clé de tri du port — parité avec l'ordre WordPress
   */
  sortDate: string;
  aParaitre?: boolean | null;
  authors?: (number | Author)[] | null;
  collection?: (number | null) | Collection;
  cover?: (number | null) | Media;
  /**
   * URL OVH de repli si le rapatriement du média a échoué (risque 11 du plan).
   */
  coverFallbackUrl?: string | null;
  tablePdf?: (number | null) | Media;
  extraitPdf?: (number | null) | Media;
  buy?: {
    boutiqueUrl?: string | null;
    parislibrairies?: string | null;
    lalibrairie?: string | null;
  };
  /**
   * Commerce natif (phase 4) — actif sur le front seulement quand COMMERCE_NATIVE=1 (bascule du jour J).
   */
  commerce?: {
    /**
     * Tout ce qui est au catalogue est vendable par défaut (décision client du 13/07) — décocher pour retirer un titre de la vente en ligne. Un livre non vendable reste au catalogue (jamais retiré, cf. §Local Contracts). La disponibilité réelle reste gouvernée par le stock (0 = épuisé) et la date de parution (« à paraître » prime sur tout).
     */
    sellable?: boolean | null;
    /**
     * Champ unique pour tout ce qui se vend — livres ET produits boutique-seuls/goodies (même mécanique de décrément ensuite). Vide = pas de décompte saisi (disponible si vendable — même fallback que les goodies). Alimenté par l'import routeur mensuel (suivi « routeur ») ou saisi ici à la main (suivi « manuel », et possible aussi en suivi routeur — écrasé au prochain fichier si la fiche y figure). Le stock EST la disponibilité — pas de bascule « en stock/épuisé » séparée (décision client du 12/07) ; 0 signifie épuisé sans retirer la fiche du catalogue.
     */
    stock?: number | null;
    /**
     * Posé à « routeur » automatiquement par l'import mensuel dès qu'une fiche est appariée au fichier ; « manuel » (défaut) pour tout le reste — goodies ET livres non suivis par le routeur, traités pareil (décision client du 12/07). Une fiche « routeur » absente du fichier suivant est signalée par l'import (titre disparu du routeur) et garde ce mode tant que l'anomalie n'est pas résolue.
     */
    stockSuivi?: ('routeur' | 'manuel') | null;
    /**
     * Remplace l'ancienne règle « manifeste » au poids : un panier composé uniquement d'articles cochés bénéficie du tarif de port réduit plutôt que la grille standard (décision client du 12/07, question ouverte n°2 du plan).
     */
    reducedShippingFlag?: boolean | null;
    /**
     * Posé automatiquement par l'import stock routeur mensuel (`POST /api/books/import-stock`) — jamais saisi à la main.
     */
    stockUpdatedAt?: string | null;
  };
  /**
   * Clé d'upsert de la migration — vide pour les fiches nées dans Payload.
   */
  wpSource?: {
    site?: ('editions-sociales' | 'la-dispute') | null;
    wpId?: number | null;
    wpSlug?: string | null;
    wpDate?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Bandeau ponctuel affiché sur la page d’accueil (une campagne à la fois).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlight".
 */
export interface Highlight {
  id: number;
  titre: string;
  /**
   * Une ou deux phrases — pas de mise en forme (bandeau, pas une fiche).
   */
  texte?: string | null;
  /**
   * URL absolue ou chemin du site (ex. /souscription) — facultatif.
   */
  lien?: string | null;
  dateDebut: string;
  dateFin: string;
  /**
   * Doit être coché ET la date courante comprise dans la période pour être visible.
   */
  actif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Commandes du commerce natif — créées par le webhook Stripe, suivies ici (statut de préparation/expédition uniquement).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Généré automatiquement à la création (préfixe CMD- + id) — ne se modifie pas.
   */
  number?: string | null;
  /**
   * Seul champ modifiable au back-office — suivi de préparation (paid → prepared → shipped) ; annulation/remboursement au besoin. « Échec du paiement » : posé par le webhook (checkout.session.async_payment_failed) pour un moyen de paiement différé (ex. virement/prélèvement) dont la confirmation échoue APRÈS que checkout.session.completed s'est déjà présenté en attente — trace l'essai sans jamais décrémenter le stock (webhook route, lot 2 étape 9).
   */
  status: 'paid' | 'prepared' | 'shipped' | 'cancelled' | 'refunded' | 'failed';
  email: string;
  shippingAddress: {
    fullName: string;
    addressLine1: string;
    addressLine2?: string | null;
    postalCode: string;
    city: string;
    /**
     * Ventes restreintes FR/BE/CH (plan phase 4, étape 8).
     */
    country: 'FR' | 'BE' | 'CH';
  };
  /**
   * Dupliquée depuis la livraison par le webhook si le checkout ne collecte pas d’adresse de facturation distincte (étape 8).
   */
  billingAddress: {
    fullName: string;
    addressLine1: string;
    addressLine2?: string | null;
    postalCode: string;
    city: string;
    /**
     * Ventes restreintes FR/BE/CH (plan phase 4, étape 8).
     */
    country: 'FR' | 'BE' | 'CH';
  };
  /**
   * Snapshot au moment de la vente (titre/ISBN/prix) — indépendant d'une modification ultérieure de la fiche livre.
   */
  lines?:
    | {
        book: number | Book;
        titleSnapshot: string;
        isbnSnapshot?: string | null;
        quantity: number;
        unitPriceTTC: number;
        id?: string | null;
      }[]
    | null;
  shippingMethod: 'standard' | 'reduit' | 'offert';
  shippingCostTTC: number;
  promoCode?: (number | null) | PromoCode;
  discountTTC?: number | null;
  totalTTC: number;
  /**
   * Clé d'idempotence du webhook (étape 9) — une session ne crée jamais deux commandes.
   */
  stripeSessionId: string;
  stripePaymentIntentId?: string | null;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes".
 */
export interface PromoCode {
  id: number;
  /**
   * Normalisé en majuscules à la sauvegarde (insensible à la casse au checkout).
   */
  code: string;
  type: 'fixed_cart' | 'free_shipping';
  /**
   * Utilisé uniquement pour le type « montant fixe » — ignoré pour « livraison offerte ».
   */
  amount?: number | null;
  /**
   * Montant TTC minimum du panier pour que le code s’applique (ex. 50 € pour la livraison offerte — plan §étape 5).
   */
  minCart?: number | null;
  expiresAt?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'highlight';
        value: number | Highlight;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'promo-codes';
        value: number | PromoCode;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  edition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  edition?: T;
  origin?: T;
  presentation?: T;
  presentationLegacyHtml?: T;
  plusLoin?: T;
  plusLoinLegacyHtml?: T;
  contentTouched?: T;
  isbn?: T;
  prix?: T;
  pages?: T;
  dateParution?: T;
  sortDate?: T;
  aParaitre?: T;
  authors?: T;
  collection?: T;
  cover?: T;
  coverFallbackUrl?: T;
  tablePdf?: T;
  extraitPdf?: T;
  buy?:
    | T
    | {
        boutiqueUrl?: T;
        parislibrairies?: T;
        lalibrairie?: T;
      };
  commerce?:
    | T
    | {
        sellable?: T;
        stock?: T;
        stockSuivi?: T;
        reducedShippingFlag?: T;
        stockUpdatedAt?: T;
      };
  wpSource?:
    | T
    | {
        site?: T;
        wpId?: T;
        wpSlug?: T;
        wpDate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlight_select".
 */
export interface HighlightSelect<T extends boolean = true> {
  titre?: T;
  texte?: T;
  lien?: T;
  dateDebut?: T;
  dateFin?: T;
  actif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  status?: T;
  email?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        addressLine1?: T;
        addressLine2?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        fullName?: T;
        addressLine1?: T;
        addressLine2?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  lines?:
    | T
    | {
        book?: T;
        titleSnapshot?: T;
        isbnSnapshot?: T;
        quantity?: T;
        unitPriceTTC?: T;
        id?: T;
      };
  shippingMethod?: T;
  shippingCostTTC?: T;
  promoCode?: T;
  discountTTC?: T;
  totalTTC?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes_select".
 */
export interface PromoCodesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  amount?: T;
  minCart?: T;
  expiresAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reglages-boutique".
 */
export interface ReglagesBoutique {
  id: number;
  /**
   * En dessous de ce nombre d'exemplaires (`commerce.stock` des fiches Livres), un article est signalé comme stock bas — usage réservé aux étapes ultérieures du plan (back-office, étape 10) ; ce lot ne pose que le réglage.
   */
  seuilAlerteStockBas: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Texte des trois pages légales. Un onglet vide laisse la page servie avec son texte par défaut (placeholders [À COMPLÉTER…] inclus).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages-legales".
 */
export interface PagesLegales {
  id: number;
  /**
   * Remplace tout le corps de la page /cgv (chapeau compris) — le titre et le fil d’ariane restent fixes. Vide = texte actuel du site.
   */
  cgv?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Remplace tout le corps de la page /mentions-legales (chapeau compris). Vide = texte actuel du site, avec ses placeholders [À COMPLÉTER…].
   */
  mentionsLegales?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Remplace tout le corps de la page /confidentialite (chapeau compris). Vide = texte actuel du site.
   */
  confidentialite?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Pied de page, réseaux sociaux et référencement par défaut. Un champ vide = le texte actuel du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reglages-site".
 */
export interface ReglagesSite {
  id: number;
  footer?: {
    /**
     * Sous « Les Éditions sociales × La Dispute » (le nom reste fixe). Vide = texte actuel.
     */
    adresse?: string | null;
    /**
     * Vide = texte actuel.
     */
    texteDiffusion?: string | null;
  };
  /**
   * Affichés dans le pied de page (cellule « Suivez-nous »). Aucun lien = pied de page inchangé.
   */
  reseauxSociaux?:
    | {
        label: string;
        /**
         * URL complète (https://…).
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Titre de la page d’accueil et suffixe des titres de pages (« Page — Titre »). Vide = titre actuel.
     */
    titreParDefaut?: string | null;
    /**
     * Méta-description par défaut du site. Vide = description actuelle.
     */
    descriptionParDefaut?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textes de la page /a-propos. Un champ vide = le texte actuel du site ; les couleurs et la mise en page restent en code.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-a-propos".
 */
export interface PageAPropos {
  id: number;
  heros?: {
    /**
     * Vide = titre actuel.
     */
    titre?: string | null;
    /**
     * Vide = texte actuel.
     */
    intro?: string | null;
  };
  citation?: {
    /**
     * Guillemets compris. Vide = citation actuelle.
     */
    texte?: string | null;
    /**
     * Vide = attribution actuelle.
     */
    attribution?: string | null;
  };
  /**
   * Surcharge les textes de la section « Deux maisons ». Maison absente ou champ vide = texte actuel ; les couleurs restent en code.
   */
  maisons?:
    | {
        maison: 'editions-sociales' | 'la-dispute';
        nom?: string | null;
        tagline?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Remplacent la section « Le catalogue » (titre, texte et boutons actuels). Aucune section = section actuelle.
   */
  sections?:
    | {
        titre: string;
        contenu?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reglages-boutique_select".
 */
export interface ReglagesBoutiqueSelect<T extends boolean = true> {
  seuilAlerteStockBas?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages-legales_select".
 */
export interface PagesLegalesSelect<T extends boolean = true> {
  cgv?: T;
  mentionsLegales?: T;
  confidentialite?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reglages-site_select".
 */
export interface ReglagesSiteSelect<T extends boolean = true> {
  footer?:
    | T
    | {
        adresse?: T;
        texteDiffusion?: T;
      };
  reseauxSociaux?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titreParDefaut?: T;
        descriptionParDefaut?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-a-propos_select".
 */
export interface PageAProposSelect<T extends boolean = true> {
  heros?:
    | T
    | {
        titre?: T;
        intro?: T;
      };
  citation?:
    | T
    | {
        texte?: T;
        attribution?: T;
      };
  maisons?:
    | T
    | {
        maison?: T;
        nom?: T;
        tagline?: T;
        description?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        titre?: T;
        contenu?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}