/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    books: Book;
    orders: Order;
    'virements-souscription': VirementsSouscription;
    authors: Author;
    libelles: Libelle;
    media: Media;
    ebooks: Ebook;
    highlight: Highlight;
    rencontres: Rencontre;
    'promo-codes': PromoCode;
    users: User;
    'import-runs': ImportRun;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    books: BooksSelect<false> | BooksSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'virements-souscription': VirementsSouscriptionSelect<false> | VirementsSouscriptionSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    libelles: LibellesSelect<false> | LibellesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    ebooks: EbooksSelect<false> | EbooksSelect<true>;
    highlight: HighlightSelect<false> | HighlightSelect<true>;
    rencontres: RencontresSelect<false> | RencontresSelect<true>;
    'promo-codes': PromoCodesSelect<false> | PromoCodesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'import-runs': ImportRunsSelect<false> | ImportRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'page-souscription': PageSouscription;
    'reglages-boutique': ReglagesBoutique;
    'page-a-propos': PageAPropos;
    'page-contact': PageContact;
    'pages-legales': PagesLegales;
  };
  globalsSelect: {
    'page-souscription': PageSouscriptionSelect<false> | PageSouscriptionSelect<true>;
    'reglages-boutique': ReglagesBoutiqueSelect<false> | ReglagesBoutiqueSelect<true>;
    'page-a-propos': PageAProposSelect<false> | PageAProposSelect<true>;
    'page-contact': PageContactSelect<false> | PageContactSelect<true>;
    'pages-legales': PagesLegalesSelect<false> | PagesLegalesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title: string;
  /**
   * Adresse de la fiche. Ne pas modifier après publication : les liens déjà partagés casseraient.
   */
  slug: string;
  edition?: ('editions-sociales' | 'la-dispute') | null;
  authors?: (number | Author)[] | null;
  /**
   * Thèmes du catalogue (plusieurs possibles). Liste gérée sous Catalogue → Libellés.
   */
  libelles?: (number | Libelle)[] | null;
  /**
   * Une date future rend le livre « à paraître » : achat bloqué, sauf précommande ouverte.
   */
  dateParution: string;
  /**
   * ISBN-13 ou ISBN-10, tirets facultatifs.
   */
  isbn?: string | null;
  pages?: number | null;
  /**
   * Glissez-déposez une image. Texte alternatif généré automatiquement.
   */
  cover?: (number | null) | Media;
  /**
   * Glissez-déposez un PDF. Texte alternatif généré automatiquement.
   */
  tablePdf?: (number | null) | Media;
  /**
   * Glissez-déposez un PDF. Texte alternatif généré automatiquement.
   */
  extraitPdf?: (number | null) | Media;
  /**
   * Si ce champ paraît vide, l’ancien texte reste affiché sur le site. Dès que vous enregistrez ici, il le remplace.
   */
  presentation: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Affiché dans l’onglet « Pour aller plus loin » — l’onglet n’apparaît que si ce champ est rempli.
   */
  plusLoin?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Affichées dans l’onglet « La presse en parle ». Aucune citation ni vidéo = pas d’onglet.
   */
  presse?:
    | {
        /**
         * Sans guillemets — ils sont ajoutés à l’affichage.
         */
        citation: string;
        /**
         * Ex. « Mediapart ».
         */
        source: string;
        /**
         * Texte libre, ex. « 10 juin 2026 ».
         */
        date?: string | null;
        /**
         * Article en ligne (facultatif).
         */
        lien?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL YouTube (watch, youtu.be ou embed).
   */
  video?: string | null;
  /**
   * Affichée dans l’onglet « Table des matières » ; le PDF téléversé plus haut reste aussi proposé en lien.
   */
  tableMatieres?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Prix TTC — la TVA 5,5 % est incluse et jamais recalculée au checkout.
   */
  prix?: number | null;
  origin: 'catalogue' | 'boutique';
  commerce?: {
    /**
     * Vide = indisponible à la commande ; 0 = épuisé, retiré de la vente sans quitter le catalogue ; > 0 = commandable.
     */
    stock?: number | null;
    /**
     * Décocher retire le titre de la vente en ligne sans le retirer du catalogue.
     */
    sellable?: boolean | null;
    /**
     * Un panier composé uniquement d'articles cochés bénéficie du tarif de port réduit.
     */
    reducedShippingFlag?: boolean | null;
    /**
     * Un livre à paraître devient achetable en précommande dès que cette case est cochée — expédié à la parution. Sans effet sur un livre déjà paru.
     */
    preorder?: boolean | null;
    /**
     * Posé automatiquement à « routeur » par l'import mensuel ; « manuel » (défaut) sinon.
     */
    stockSuivi?: ('routeur' | 'manuel') | null;
    /**
     * Mis à jour automatiquement par l’import mensuel — jamais saisi à la main.
     */
    stockUpdatedAt?: string | null;
  };
  buy?: {
    boutiqueUrl?: string | null;
    /**
     * Se remplit automatiquement depuis l’ISBN dès que le livre est référencé chez ce libraire. Un lien collé à la main reste prioritaire.
     */
    parislibrairies?: string | null;
    /**
     * Se remplit automatiquement depuis l’ISBN dès que le livre est référencé chez ce libraire. Un lien collé à la main reste prioritaire.
     */
    lalibrairie?: string | null;
  };
  contentTouched?: boolean | null;
  wpSource?: {
    site?: ('editions-sociales' | 'la-dispute') | null;
    wpId?: number | null;
    wpSlug?: string | null;
    wpDate?: string | null;
  };
  coverFallbackUrl?: string | null;
  sortDate: string;
  presentationLegacyHtml?: string | null;
  plusLoinLegacyHtml?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Forme « Prénom Nom »
   */
  name: string;
  /**
   * Utilisé dans les liens de filtre du catalogue. Ne pas modifier après publication : les liens déjà partagés casseraient.
   */
  slug: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "libelles".
 */
export interface Libelle {
  id: number;
  name: string;
  /**
   * Utilisé dans les liens de filtre du catalogue. Ne pas modifier après publication : les liens déjà partagés casseraient.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pour remplacer une image : téléversez un nouveau fichier plutôt que de la recadrer en place — sinon elle garde la même adresse et peut rester invisible en ligne pendant longtemps.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Rempli automatiquement depuis le titre et les auteur·rice·s du livre.
   */
  alt?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Créées automatiquement au paiement. Vous ne modifiez ici que le statut de préparation. Un panier mixte (paru + précommande) peut créer deux commandes distinctes — voir « Type ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Généré automatiquement à la création — ne se modifie pas.
   */
  number?: string | null;
  /**
   * Seul champ modifiable ici — suivi de préparation (payée → préparée → expédiée), plus annulation/remboursement au besoin. « Échec du paiement » est posé automatiquement pour un paiement différé (virement, prélèvement) qui échoue.
   */
  status: 'paid' | 'prepared' | 'shipped' | 'cancelled' | 'refunded' | 'failed';
  /**
   * Commande normale, précommande (article à paraître) ou don. Un panier mixte (paru + précommande) crée une commande de chaque type pour un même paiement. « Don » : jamais compté dans le chiffre d’affaires, mais suivi en préparation et expédition comme une commande normale.
   */
  orderType: 'commande' | 'precommande' | 'don';
  paidAt?: string | null;
  email: string;
  /**
   * Peut être vide : non collecté sur les commandes anciennes, les dons et l’historique repris.
   */
  phone?: string | null;
  shippingAddress: {
    fullName: string;
    addressLine1: string;
    addressLine2?: string | null;
    postalCode: string;
    city: string;
    country: 'FR' | 'BE' | 'CH';
  };
  /**
   * Titre, ISBN et prix tels qu’au moment de la vente — ne changent pas si la fiche livre est modifiée depuis.
   */
  lines?:
    | {
        book: number | Book;
        titleSnapshot: string;
        isbnSnapshot?: string | null;
        quantity: number;
        unitPriceTTC: number;
        id?: string | null;
      }[]
    | null;
  shippingMethod: 'standard' | 'reduit' | 'offert';
  shippingCostTTC: number;
  promoCode?: (number | null) | PromoCode;
  discountTTC?: number | null;
  totalTTC: number;
  /**
   * Identique à l’adresse de livraison si aucune adresse de facturation distincte n’a été saisie.
   */
  billingAddress: {
    fullName: string;
    addressLine1: string;
    addressLine2?: string | null;
    postalCode: string;
    city: string;
    country: 'FR' | 'BE' | 'CH';
  };
  /**
   * Identifiant du paiement Stripe. Un panier mixte peut produire deux commandes avec le même identifiant (une « Commande » + une « Précommande »).
   */
  stripeSessionId: string;
  stripePaymentIntentId?: string | null;
  /**
   * Indique si le stock de cette commande a déjà été décompté. Ne se modifie jamais à la main.
   */
  stockDecremented: boolean;
  /**
   * Indique si l’e-mail de confirmation a déjà été envoyé. Ne se modifie jamais à la main.
   */
  confirmationSent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes".
 */
export interface PromoCode {
  id: number;
  /**
   * Normalisé en majuscules à la sauvegarde (insensible à la casse au checkout).
   */
  code: string;
  type: 'fixed_cart' | 'free_shipping';
  /**
   * Utilisé uniquement pour le type « montant fixe » — ignoré pour « livraison offerte ».
   */
  amount?: number | null;
  /**
   * Montant TTC minimum du panier pour que le code s’applique (ex. 50 € pour la livraison offerte).
   */
  minCart?: number | null;
  expiresAt?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Virements bancaires reçus hors site — comptés dans la jauge de la page Souscription. Réimporter le fichier Excel en entier après chaque ajout ne crée jamais de doublon.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "virements-souscription".
 */
export interface VirementsSouscription {
  id: number;
  /**
   * Jour du virement, sans l’heure.
   */
  date: string;
  nom: string;
  /**
   * En euros (ex. 50 ou 37,50).
   */
  montantEUR: number;
  /**
   * Reconnu automatiquement à l’import depuis la colonne « choix de la souscription » — « Autre » si elle ne correspond à aucun palier connu.
   */
  palier?:
    | (
        | 'palier-15'
        | 'palier-35'
        | 'palier-50'
        | 'palier-75'
        | 'palier-100'
        | 'palier-200'
        | 'palier-300'
        | 'palier-500'
        | 'palier-1000'
        | 'autre'
      )
    | null;
  /**
   * Texte brut de la colonne du fichier, conservé même si le palier ci-dessus est reconnu.
   */
  choixSaisi?: string | null;
  email?: string | null;
  /**
   * Libellé du virement, commentaire de l’équipe — informatif.
   */
  reference?: string | null;
  /**
   * Évite les doublons lors du réimport. Vide pour une ligne saisie à la main — jamais écrasée par un import.
   */
  cleImport?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Téléversez le fichier, choisissez le titre concerné : toute commande payée contenant ce titre reçoit ensuite un lien de téléchargement dans son e-mail de confirmation. Pour remplacer un fichier, ouvrez sa fiche et téléversez le nouveau — les liens déjà envoyés restent valables.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ebooks".
 */
export interface Ebook {
  id: number;
  /**
   * Un seul fichier par titre — pour le remplacer, téléversez le nouveau ici plutôt que de créer une seconde fiche.
   */
  livre: number | Book;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlight".
 */
export interface Highlight {
  id: number;
  titre: string;
  /**
   * Une ou deux phrases — pas de mise en forme (bandeau, pas une fiche).
   */
  texte?: string | null;
  /**
   * Couleur d’accent à gauche du bandeau. Sans effet si le lien pointe vers /souscription.
   */
  couleur?: ('pop-pink' | 'pop-teal' | 'pop-orange' | 'pop-yellow') | null;
  /**
   * URL absolue ou chemin du site (ex. /souscription) — facultatif.
   */
  lien?: string | null;
  /**
   * Texte du bouton — utilisé seulement si un lien est renseigné.
   */
  lienLibelle?: string | null;
  dateDebut: string;
  dateFin: string;
  /**
   * Doit être coché ET la date courante comprise dans la période pour être visible.
   */
  actif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rencontres".
 */
export interface Rencontre {
  id: number;
  titre: string;
  date: string;
  /**
   * Texte libre, ex. « 15h-16h30 ».
   */
  heure?: string | null;
  lieu: string;
  ville: string;
  /**
   * Livre présenté — sa couverture sert d’image de l’événement par défaut.
   */
  livre?: (number | null) | Book;
  /**
   * Remplace la couverture du livre si renseignée.
   */
  image?: (number | null) | Media;
  /**
   * Affiche l’événement en grande carte pleine largeur, en tête de l’agenda.
   */
  pleinCadre?: boolean | null;
  /**
   * Texte libre — ex. « Gouverner les juges, Vincent Sizaire ; avec Marie Dosé et Fabrice Arfi ».
   */
  intervenants?: string | null;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Historique des imports du fichier stock routeur, créé automatiquement à chaque import. Le dernier est déjà résumé sur le tableau de bord — consultation seule.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs".
 */
export interface ImportRun {
  id: number;
  /**
   * Lignes exploitables du fichier routeur (EAN présent).
   */
  nbLignes: number;
  /**
   * Fiches appariées par ISBN normalisé et mises à jour.
   */
  nbMatchees: number;
  /**
   * Les non-appariés se téléchargent en CSV via le tableau de bord.
   */
  rapport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'virements-souscription';
        value: number | VirementsSouscription;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'libelles';
        value: number | Libelle;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'ebooks';
        value: number | Ebook;
      } | null)
    | ({
        relationTo: 'highlight';
        value: number | Highlight;
      } | null)
    | ({
        relationTo: 'rencontres';
        value: number | Rencontre;
      } | null)
    | ({
        relationTo: 'promo-codes';
        value: number | PromoCode;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'import-runs';
        value: number | ImportRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  edition?: T;
  authors?: T;
  libelles?: T;
  dateParution?: T;
  isbn?: T;
  pages?: T;
  cover?: T;
  tablePdf?: T;
  extraitPdf?: T;
  presentation?: T;
  plusLoin?: T;
  presse?:
    | T
    | {
        citation?: T;
        source?: T;
        date?: T;
        lien?: T;
        id?: T;
      };
  video?: T;
  tableMatieres?: T;
  prix?: T;
  origin?: T;
  commerce?:
    | T
    | {
        stock?: T;
        sellable?: T;
        reducedShippingFlag?: T;
        preorder?: T;
        stockSuivi?: T;
        stockUpdatedAt?: T;
      };
  buy?:
    | T
    | {
        boutiqueUrl?: T;
        parislibrairies?: T;
        lalibrairie?: T;
      };
  contentTouched?: T;
  wpSource?:
    | T
    | {
        site?: T;
        wpId?: T;
        wpSlug?: T;
        wpDate?: T;
      };
  coverFallbackUrl?: T;
  sortDate?: T;
  presentationLegacyHtml?: T;
  plusLoinLegacyHtml?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  status?: T;
  orderType?: T;
  paidAt?: T;
  email?: T;
  phone?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        addressLine1?: T;
        addressLine2?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  lines?:
    | T
    | {
        book?: T;
        titleSnapshot?: T;
        isbnSnapshot?: T;
        quantity?: T;
        unitPriceTTC?: T;
        id?: T;
      };
  shippingMethod?: T;
  shippingCostTTC?: T;
  promoCode?: T;
  discountTTC?: T;
  totalTTC?: T;
  billingAddress?:
    | T
    | {
        fullName?: T;
        addressLine1?: T;
        addressLine2?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  stockDecremented?: T;
  confirmationSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "virements-souscription_select".
 */
export interface VirementsSouscriptionSelect<T extends boolean = true> {
  date?: T;
  nom?: T;
  montantEUR?: T;
  palier?: T;
  choixSaisi?: T;
  email?: T;
  reference?: T;
  cleImport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "libelles_select".
 */
export interface LibellesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ebooks_select".
 */
export interface EbooksSelect<T extends boolean = true> {
  livre?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlight_select".
 */
export interface HighlightSelect<T extends boolean = true> {
  titre?: T;
  texte?: T;
  couleur?: T;
  lien?: T;
  lienLibelle?: T;
  dateDebut?: T;
  dateFin?: T;
  actif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rencontres_select".
 */
export interface RencontresSelect<T extends boolean = true> {
  titre?: T;
  date?: T;
  heure?: T;
  lieu?: T;
  ville?: T;
  livre?: T;
  image?: T;
  pleinCadre?: T;
  intervenants?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes_select".
 */
export interface PromoCodesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  amount?: T;
  minCart?: T;
  expiresAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs_select".
 */
export interface ImportRunsSelect<T extends boolean = true> {
  nbLignes?: T;
  nbMatchees?: T;
  rapport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Titre, récit et contreparties de la page /souscription. Un champ vide garde le contenu actuel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-souscription".
 */
export interface PageSouscription {
  id: number;
  /**
   * Vide = « 100 ans ».
   */
  titre?: string | null;
  /**
   * Vide = « d’édition marxiste : ».
   */
  sousTitre?: string | null;
  /**
   * Vide = « aidez-nous à poursuivre l’histoire. ».
   */
  demande?: string | null;
  danger?: {
    /**
     * Vide = titre actuel.
     */
    titre?: string | null;
    /**
     * Optionnel, affichée en italique sous le titre. Vide = pas de 2ᵉ ligne (ou la 2ᵉ ligne actuelle).
     */
    titreItalique?: string | null;
    /**
     * Vide = texte actuel. Le gras est repris sur le site ; le souligné n’a aucun effet visuel.
     */
    corps?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  guerre?: {
    /**
     * Vide = titre actuel.
     */
    titre?: string | null;
    /**
     * Optionnel, affichée en italique sous le titre. Vide = pas de 2ᵉ ligne (ou la 2ᵉ ligne actuelle).
     */
    titreItalique?: string | null;
    /**
     * Vide = texte actuel. Le gras est repris sur le site ; le souligné n’a aucun effet visuel.
     */
    corps?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  maisons?: {
    /**
     * Vide = titre actuel.
     */
    titre?: string | null;
    /**
     * Optionnel, affichée en italique sous le titre. Vide = pas de 2ᵉ ligne (ou la 2ᵉ ligne actuelle).
     */
    titreItalique?: string | null;
    /**
     * Vide = texte actuel. Le gras est repris sur le site ; le souligné n’a aucun effet visuel.
     */
    corps?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  appel?: {
    /**
     * Vide = titre actuel.
     */
    titre?: string | null;
    /**
     * Optionnel, affichée en italique sous le titre. Vide = pas de 2ᵉ ligne (ou la 2ᵉ ligne actuelle).
     */
    titreItalique?: string | null;
    /**
     * Vide = texte actuel. Le gras est repris sur le site ; le souligné n’a aucun effet visuel.
     */
    corps?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Les montants des trois paliers restent fixes ; seuls le titre court et sa description se modifient ici.
   */
  objectifs?: {
    /**
     * Vide = « On sauve les meubles ».
     */
    titre50?: string | null;
    /**
     * Vide = texte actuel.
     */
    descriptif50?: string | null;
    /**
     * Vide = « On résiste ».
     */
    titre80?: string | null;
    /**
     * Vide = texte actuel.
     */
    descriptif80?: string | null;
    /**
     * Vide = « On construit ».
     */
    titre100?: string | null;
    /**
     * Vide = texte actuel.
     */
    descriptif100?: string | null;
  };
  /**
   * Une entrée par palier à modifier — remplace le contenu de sa carte, les autres cartes restent inchangées. Montant et intitulé viennent du palier choisi et ne s’éditent pas ici ; l’ordre de ce tableau n’a aucun effet sur la page.
   */
  contreparties?:
    | {
        tierId:
          | 'palier-15'
          | 'palier-35'
          | 'palier-50'
          | 'palier-75'
          | 'palier-100'
          | 'palier-200'
          | 'palier-300'
          | 'palier-500'
          | 'palier-1000';
        /**
         * Une ligne par élément. Une ligne commençant par « ou » devient une alternative à la précédente (affichée « ou … », sans séparateur « + »).
         */
        items?:
          | {
              texte: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Carrousel en fin de page — l’ordre de saisie est l’ordre d’affichage, glissez les entrées pour réordonner. Aucun visuel saisi = section absente de la page.
   */
  soutiens?:
    | {
        /**
         * Photo, logo ou visuel de soutien.
         */
        image: number | Media;
        /**
         * Optionnel — sert aussi de texte alternatif de l’image.
         */
        legende?: string | null;
        /**
         * Optionnel — URL complète (https://…) vers laquelle le visuel renvoie.
         */
        lien?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reglages-boutique".
 */
export interface ReglagesBoutique {
  id: number;
  /**
   * En dessous de ce nombre d’exemplaires, un livre est signalé « stock bas » sur le tableau de bord et la page Stock.
   */
  seuilAlerteStockBas: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textes des pages /editions/editions-sociales et /editions/la-dispute.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-a-propos".
 */
export interface PageAPropos {
  id: number;
  /**
   * Textes propres à chaque maison. Maison absente ou champ vide = texte actuel.
   */
  maisons?:
    | {
        maison: 'editions-sociales' | 'la-dispute';
        nom?: string | null;
        tagline?: string | null;
        description?: string | null;
        /**
         * Une ligne par personne, listée dans cet ordre. Aucune ligne = liste actuelle de cette maison.
         */
        bureau?:
          | {
              nom: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  equipe?: {
    /**
     * Liste des noms séparés par des virgules (ex. « A, B et C »), affichée à l’identique sur les deux pages maisons. Vide = liste actuelle.
     */
    permanente?: string | null;
  };
  /**
   * Bloc identique sur les deux pages maisons (pas de bureau éditorial concerné ici).
   */
  depotManuscrit?: {
    /**
     * Utilisée dans la phrase d’accroche par défaut ci-dessous. Vide = adresse actuelle.
     */
    email?: string | null;
    /**
     * Remplace entièrement le texte par défaut, adresse e-mail comprise. Vide = texte actuel.
     */
    texte?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textes de la page /contact. Un champ vide = le texte actuel du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact".
 */
export interface PageContact {
  id: number;
  /**
   * Vide = titre actuel.
   */
  titre?: string | null;
  /**
   * Chapeau sous le titre. Vide = texte actuel.
   */
  intro?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages-legales".
 */
export interface PagesLegales {
  id: number;
  footer?: {
    /**
     * Sous « Les Éditions sociales × La Dispute » (le nom reste fixe). Vide = texte actuel.
     */
    adresse?: string | null;
  };
  /**
   * Affichés dans le pied de page (cellule « Suivez-nous »). Aucun lien = pied de page inchangé.
   */
  reseauxSociaux?:
    | {
        label: string;
        /**
         * URL complète (https://…).
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Titre de la page d’accueil et suffixe des titres de pages (« Page — Titre »). Vide = titre actuel.
     */
    titreParDefaut?: string | null;
    /**
     * Méta-description par défaut du site. Vide = description actuelle.
     */
    descriptionParDefaut?: string | null;
  };
  /**
   * Affiché sur la fiche produit, le panier et la page de remerciement — vide = « entre 48 h et 10 jours ». L’e-mail de confirmation garde toujours le texte par défaut.
   */
  livraisonDelai?: string | null;
  /**
   * Remplace tout le corps de la page /cgv (chapeau compris) — le titre et le fil d’ariane restent fixes. Vide = texte actuel du site.
   */
  cgv?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Remplace tout le corps de la page /mentions-legales (chapeau compris). Vide = texte actuel du site (identité légale de l’éditeur).
   */
  mentionsLegales?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Remplace tout le corps de la page /confidentialite (chapeau compris). Vide = texte actuel du site.
   */
  confidentialite?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-souscription_select".
 */
export interface PageSouscriptionSelect<T extends boolean = true> {
  titre?: T;
  sousTitre?: T;
  demande?: T;
  danger?:
    | T
    | {
        titre?: T;
        titreItalique?: T;
        corps?: T;
      };
  guerre?:
    | T
    | {
        titre?: T;
        titreItalique?: T;
        corps?: T;
      };
  maisons?:
    | T
    | {
        titre?: T;
        titreItalique?: T;
        corps?: T;
      };
  appel?:
    | T
    | {
        titre?: T;
        titreItalique?: T;
        corps?: T;
      };
  objectifs?:
    | T
    | {
        titre50?: T;
        descriptif50?: T;
        titre80?: T;
        descriptif80?: T;
        titre100?: T;
        descriptif100?: T;
      };
  contreparties?:
    | T
    | {
        tierId?: T;
        items?:
          | T
          | {
              texte?: T;
              id?: T;
            };
        id?: T;
      };
  soutiens?:
    | T
    | {
        image?: T;
        legende?: T;
        lien?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reglages-boutique_select".
 */
export interface ReglagesBoutiqueSelect<T extends boolean = true> {
  seuilAlerteStockBas?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-a-propos_select".
 */
export interface PageAProposSelect<T extends boolean = true> {
  maisons?:
    | T
    | {
        maison?: T;
        nom?: T;
        tagline?: T;
        description?: T;
        bureau?:
          | T
          | {
              nom?: T;
              id?: T;
            };
        id?: T;
      };
  equipe?:
    | T
    | {
        permanente?: T;
      };
  depotManuscrit?:
    | T
    | {
        email?: T;
        texte?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact_select".
 */
export interface PageContactSelect<T extends boolean = true> {
  titre?: T;
  intro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages-legales_select".
 */
export interface PagesLegalesSelect<T extends boolean = true> {
  footer?:
    | T
    | {
        adresse?: T;
      };
  reseauxSociaux?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titreParDefaut?: T;
        descriptionParDefaut?: T;
      };
  livraisonDelai?: T;
  cgv?: T;
  mentionsLegales?: T;
  confidentialite?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}