/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    books: Book;
    orders: Order;
    authors: Author;
    libelles: Libelle;
    media: Media;
    'promo-codes': PromoCode;
    'import-runs': ImportRun;
    highlight: Highlight;
    rencontres: Rencontre;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    books: BooksSelect<false> | BooksSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    libelles: LibellesSelect<false> | LibellesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'promo-codes': PromoCodesSelect<false> | PromoCodesSelect<true>;
    'import-runs': ImportRunsSelect<false> | ImportRunsSelect<true>;
    highlight: HighlightSelect<false> | HighlightSelect<true>;
    rencontres: RencontresSelect<false> | RencontresSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'reglages-boutique': ReglagesBoutique;
    'page-a-propos': PageAPropos;
    'page-souscription': PageSouscription;
    'pages-legales': PagesLegales;
  };
  globalsSelect: {
    'reglages-boutique': ReglagesBoutiqueSelect<false> | ReglagesBoutiqueSelect<true>;
    'page-a-propos': PageAProposSelect<false> | PageAProposSelect<true>;
    'page-souscription': PageSouscriptionSelect<false> | PageSouscriptionSelect<true>;
    'pages-legales': PagesLegalesSelect<false> | PagesLegalesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title: string;
  /**
   * Prérempli depuis le titre — ne pas modifier après publication
   */
  slug: string;
  edition?: ('editions-sociales' | 'la-dispute') | null;
  authors?: (number | Author)[] | null;
  /**
   * Thèmes du catalogue (plusieurs possibles). Liste gérée sous Catalogue → Libellés.
   */
  libelles?: (number | Libelle)[] | null;
  /**
   * Téléversez une image (glisser-déposer ou « Créer »). Pas de réutilisation depuis la bibliothèque — le texte alternatif est généré automatiquement.
   */
  cover?: (number | null) | Media;
  /**
   * Téléversez un PDF (glisser-déposer ou « Créer »). Pas de réutilisation depuis la bibliothèque — le texte alternatif est généré automatiquement.
   */
  tablePdf?: (number | null) | Media;
  /**
   * Téléversez un PDF (glisser-déposer ou « Créer »). Pas de réutilisation depuis la bibliothèque — le texte alternatif est généré automatiquement.
   */
  extraitPdf?: (number | null) | Media;
  /**
   * À la première sauvegarde humaine, ce texte Lexical remplace le HTML WordPress d’origine sur le site.
   */
  presentation: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  plusLoin?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Citations affichées dans l’onglet « La presse en parle » de la fiche. Aucune citation ni vidéo = pas d’onglet.
   */
  presse?:
    | {
        /**
         * Sans guillemets — ils sont ajoutés à l’affichage.
         */
        citation: string;
        /**
         * Ex. « Mediapart ».
         */
        source: string;
        /**
         * Texte libre, ex. « 10 juin 2026 ».
         */
        date?: string | null;
        /**
         * Article en ligne (facultatif).
         */
        lien?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL YouTube (watch, youtu.be ou embed) — intégrée sous les citations de l’onglet « La presse en parle ».
   */
  video?: string | null;
  /**
   * Affichée dans l’onglet « Table des matières » de la fiche ; le PDF téléversé plus haut reste proposé en lien.
   */
  tableMatieres?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  dateParution: string;
  aParaitre?: boolean | null;
  /**
   * ISBN-13 (ou ISBN-10). Tirets facultatifs — ex. 978-2-35367-036-9. La clé de contrôle est vérifiée.
   */
  isbn?: string | null;
  pages?: number | null;
  /**
   * Prix TTC — la TVA 5,5 % est incluse et jamais recalculée au checkout.
   */
  prix?: number | null;
  origin: 'catalogue' | 'boutique';
  buy?: {
    boutiqueUrl?: string | null;
    parislibrairies?: string | null;
    lalibrairie?: string | null;
  };
  /**
   * Vente en ligne native — pilote le panier et le checkout du site.
   */
  commerce?: {
    /**
     * Vendable en ligne par défaut ; décocher retire le titre de la vente sans le retirer du catalogue.
     */
    sellable?: boolean | null;
    /**
     * Un panier composé uniquement d'articles cochés bénéficie du tarif de port réduit.
     */
    reducedShippingFlag?: boolean | null;
    /**
     * Un livre « à paraître » (parution future) devient achetable en précommande dans le panier natif dès que cette case est cochée — expédié à la parution. Sans effet sur une fiche déjà parue. Sans cette case, un livre à paraître reste refusé à la vente comme aujourd'hui.
     */
    preorder?: boolean | null;
    /**
     * Champ unique livres + boutique ; vide = pas de décompte ; 0 = épuisé sans retrait du catalogue.
     */
    stock?: number | null;
    /**
     * Posé automatiquement à « routeur » par l'import mensuel ; « manuel » (défaut) sinon.
     */
    stockSuivi?: ('routeur' | 'manuel') | null;
    /**
     * Posé automatiquement par l'import stock routeur mensuel (`POST /api/books/import-stock`) — jamais saisi à la main.
     */
    stockUpdatedAt?: string | null;
  };
  contentTouched?: boolean | null;
  wpSource?: {
    site?: ('editions-sociales' | 'la-dispute') | null;
    wpId?: number | null;
    wpSlug?: string | null;
    wpDate?: string | null;
  };
  coverFallbackUrl?: string | null;
  sortDate: string;
  presentationLegacyHtml?: string | null;
  plusLoinLegacyHtml?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Forme « Prénom Nom »
   */
  name: string;
  /**
   * Prérempli depuis le nom — ne pas modifier après publication
   */
  slug: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Thèmes majeurs du catalogue (introduction, travail, genre…). Un livre peut porter plusieurs libellés.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "libelles".
 */
export interface Libelle {
  id: number;
  name: string;
  /**
   * Identifiant d’URL (`?libelle=…`) — prérempli depuis le nom.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Rempli automatiquement à la sauvegarde du livre (couverture, table des matières ou extrait — titre + auteur·rice·s). Non modifiable à la main.
   */
  alt?: string | null;
  /**
   * Clé d'idempotence de la migration
   */
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Commandes du commerce natif — créées par le webhook Stripe, suivies ici (statut de préparation/expédition uniquement). Un panier mixte (articles parus + précommande) scinde en DEUX commandes distinctes (même session Stripe, même paiement) — cf. « Type ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Généré automatiquement à la création (préfixe CMD- + id) — ne se modifie pas.
   */
  number?: string | null;
  /**
   * Commande normale (articles parus) ou précommande (articles à paraître avec « Ouvert à la précommande » coché) — posé par le webhook selon la scission du panier au paiement (client 2026-08-20). Un panier mixte produit UNE commande de chaque type, même session/paiement Stripe, chacune avec SES lignes et SES frais de port.
   */
  orderType: 'commande' | 'precommande';
  /**
   * Seul champ modifiable au back-office — suivi de préparation (paid → prepared → shipped) ; annulation/remboursement au besoin. « Échec du paiement » : posé par le webhook (checkout.session.async_payment_failed) pour un moyen de paiement différé (ex. virement/prélèvement) dont la confirmation échoue APRÈS que checkout.session.completed s'est déjà présenté en attente — trace l'essai sans jamais décrémenter le stock (webhook route, lot 2 étape 9).
   */
  status: 'paid' | 'prepared' | 'shipped' | 'cancelled' | 'refunded' | 'failed';
  email: string;
  shippingAddress: {
    fullName: string;
    addressLine1: string;
    addressLine2?: string | null;
    postalCode: string;
    city: string;
    /**
     * Ventes restreintes FR/BE/CH (plan phase 4, étape 8).
     */
    country: 'FR' | 'BE' | 'CH';
  };
  /**
   * Dupliquée depuis la livraison par le webhook si le checkout ne collecte pas d’adresse de facturation distincte (étape 8).
   */
  billingAddress: {
    fullName: string;
    addressLine1: string;
    addressLine2?: string | null;
    postalCode: string;
    city: string;
    /**
     * Ventes restreintes FR/BE/CH (plan phase 4, étape 8).
     */
    country: 'FR' | 'BE' | 'CH';
  };
  /**
   * Snapshot au moment de la vente (titre/ISBN/prix) — indépendant d'une modification ultérieure de la fiche livre.
   */
  lines?:
    | {
        book: number | Book;
        titleSnapshot: string;
        isbnSnapshot?: string | null;
        quantity: number;
        unitPriceTTC: number;
        id?: string | null;
      }[]
    | null;
  shippingMethod: 'standard' | 'reduit' | 'offert';
  shippingCostTTC: number;
  promoCode?: (number | null) | PromoCode;
  discountTTC?: number | null;
  totalTTC: number;
  /**
   * Clé d'idempotence du webhook avec « Type » (étape 9, étendue 2026-08-20) — une même session ne crée jamais deux commandes du MÊME type, mais peut légitimement porter DEUX commandes (une « Commande » + une « Précommande ») pour un panier mixte.
   */
  stripeSessionId: string;
  stripePaymentIntentId?: string | null;
  paidAt?: string | null;
  /**
   * Marqueur technique du webhook (issue #64 — reprise après échec partiel) : le stock des lignes de cette commande a-t-il déjà été décrémenté ? Un rejeu Stripe ne redécrémente jamais tant que ce marqueur est vrai. Ne se modifie jamais à la main.
   */
  stockDecremented: boolean;
  /**
   * Marqueur technique du webhook (issue #64) : l'e-mail de confirmation de cette commande a-t-il déjà été envoyé ? Ne se modifie jamais à la main.
   */
  confirmationSent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes".
 */
export interface PromoCode {
  id: number;
  /**
   * Normalisé en majuscules à la sauvegarde (insensible à la casse au checkout).
   */
  code: string;
  type: 'fixed_cart' | 'free_shipping';
  /**
   * Utilisé uniquement pour le type « montant fixe » — ignoré pour « livraison offerte ».
   */
  amount?: number | null;
  /**
   * Montant TTC minimum du panier pour que le code s’applique (ex. 50 € pour la livraison offerte — plan §étape 5).
   */
  minCart?: number | null;
  expiresAt?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Historique des imports mensuels du fichier stock routeur — un document par import réussi, créé automatiquement par l'import (jamais à la main). Le dernier run alimente le panneau « Import routeur » du tableau de bord.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs".
 */
export interface ImportRun {
  id: number;
  /**
   * Lignes exploitables du fichier routeur (EAN présent).
   */
  nbLignes: number;
  /**
   * Fiches appariées par ISBN normalisé et mises à jour.
   */
  nbMatchees: number;
  /**
   * Rapport complet du run (`StockImportReport`) — les non-appariés se téléchargent en CSV via le tableau de bord.
   */
  rapport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bandeau ponctuel affiché sur la page d’accueil (une campagne à la fois).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlight".
 */
export interface Highlight {
  id: number;
  titre: string;
  /**
   * Une ou deux phrases — pas de mise en forme (bandeau, pas une fiche).
   */
  texte?: string | null;
  /**
   * Couleur d'accent du bandeau (liseré à gauche du bloc). Ignorée pour la campagne souscription (lien vers /souscription), qui garde son identité sombre propre.
   */
  couleur?: ('pop-pink' | 'pop-teal' | 'pop-orange' | 'pop-yellow') | null;
  /**
   * URL absolue ou chemin du site (ex. /souscription) — facultatif.
   */
  lien?: string | null;
  /**
   * Texte du bouton — utilisé seulement si un lien est renseigné.
   */
  lienLibelle?: string | null;
  dateDebut: string;
  dateFin: string;
  /**
   * Doit être coché ET la date courante comprise dans la période pour être visible.
   */
  actif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Agenda public des rencontres (page /rencontres) — une entrée par événement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rencontres".
 */
export interface Rencontre {
  id: number;
  titre: string;
  date: string;
  /**
   * Texte libre, ex. « 15h-16h30 ».
   */
  heure?: string | null;
  lieu: string;
  ville: string;
  /**
   * Livre présenté — sa couverture sert d’image de l’événement par défaut.
   */
  livre?: (number | null) | Book;
  /**
   * Photo ou visuel de l’événement (facultatif) — remplace la couverture du livre si renseigné. Format libre.
   */
  image?: (number | null) | Media;
  /**
   * Coché : l’événement s’affiche en grande carte pleine largeur en tête de l’agenda (ex. braderie). Décoché : carte standard dans la grille 2-3 colonnes.
   */
  pleinCadre?: boolean | null;
  /**
   * Texte libre — ex. « Gouverner les juges, Vincent Sizaire ; avec Marie Dosé et Fabrice Arfi ».
   */
  intervenants?: string | null;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'libelles';
        value: number | Libelle;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'promo-codes';
        value: number | PromoCode;
      } | null)
    | ({
        relationTo: 'import-runs';
        value: number | ImportRun;
      } | null)
    | ({
        relationTo: 'highlight';
        value: number | Highlight;
      } | null)
    | ({
        relationTo: 'rencontres';
        value: number | Rencontre;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  edition?: T;
  authors?: T;
  libelles?: T;
  cover?: T;
  tablePdf?: T;
  extraitPdf?: T;
  presentation?: T;
  plusLoin?: T;
  presse?:
    | T
    | {
        citation?: T;
        source?: T;
        date?: T;
        lien?: T;
        id?: T;
      };
  video?: T;
  tableMatieres?: T;
  dateParution?: T;
  aParaitre?: T;
  isbn?: T;
  pages?: T;
  prix?: T;
  origin?: T;
  buy?:
    | T
    | {
        boutiqueUrl?: T;
        parislibrairies?: T;
        lalibrairie?: T;
      };
  commerce?:
    | T
    | {
        sellable?: T;
        reducedShippingFlag?: T;
        preorder?: T;
        stock?: T;
        stockSuivi?: T;
        stockUpdatedAt?: T;
      };
  contentTouched?: T;
  wpSource?:
    | T
    | {
        site?: T;
        wpId?: T;
        wpSlug?: T;
        wpDate?: T;
      };
  coverFallbackUrl?: T;
  sortDate?: T;
  presentationLegacyHtml?: T;
  plusLoinLegacyHtml?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  orderType?: T;
  status?: T;
  email?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        addressLine1?: T;
        addressLine2?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        fullName?: T;
        addressLine1?: T;
        addressLine2?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  lines?:
    | T
    | {
        book?: T;
        titleSnapshot?: T;
        isbnSnapshot?: T;
        quantity?: T;
        unitPriceTTC?: T;
        id?: T;
      };
  shippingMethod?: T;
  shippingCostTTC?: T;
  promoCode?: T;
  discountTTC?: T;
  totalTTC?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  paidAt?: T;
  stockDecremented?: T;
  confirmationSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "libelles_select".
 */
export interface LibellesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes_select".
 */
export interface PromoCodesSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  amount?: T;
  minCart?: T;
  expiresAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs_select".
 */
export interface ImportRunsSelect<T extends boolean = true> {
  nbLignes?: T;
  nbMatchees?: T;
  rapport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlight_select".
 */
export interface HighlightSelect<T extends boolean = true> {
  titre?: T;
  texte?: T;
  couleur?: T;
  lien?: T;
  lienLibelle?: T;
  dateDebut?: T;
  dateFin?: T;
  actif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rencontres_select".
 */
export interface RencontresSelect<T extends boolean = true> {
  titre?: T;
  date?: T;
  heure?: T;
  lieu?: T;
  ville?: T;
  livre?: T;
  image?: T;
  pleinCadre?: T;
  intervenants?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reglages-boutique".
 */
export interface ReglagesBoutique {
  id: number;
  /**
   * En dessous de ce nombre d'exemplaires (`commerce.stock` des fiches Livres), un article est signalé comme stock bas — usage réservé aux étapes ultérieures du plan (back-office, étape 10) ; ce lot ne pose que le réglage.
   */
  seuilAlerteStockBas: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textes de la page /a-propos. Un champ vide = le texte actuel du site ; les couleurs et la mise en page restent en code.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-a-propos".
 */
export interface PageAPropos {
  id: number;
  heros?: {
    /**
     * Vide = titre actuel.
     */
    titre?: string | null;
    /**
     * Vide = texte actuel.
     */
    intro?: string | null;
  };
  citation?: {
    /**
     * Guillemets compris. Vide = citation actuelle.
     */
    texte?: string | null;
    /**
     * Vide = attribution actuelle.
     */
    attribution?: string | null;
  };
  /**
   * Surcharge les textes de la section « Deux maisons ». Maison absente ou champ vide = texte actuel ; les couleurs restent en code.
   */
  maisons?:
    | {
        maison: 'editions-sociales' | 'la-dispute';
        nom?: string | null;
        tagline?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Remplacent la section « Le catalogue » (titre, texte et boutons actuels). Aucune section = section actuelle.
   */
  sections?:
    | {
        titre: string;
        contenu?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Titre, récit et contreparties de la page /souscription. Un champ vide = le contenu actuel du site ; les montants des paliers restent pilotés par le code (paiement Stripe).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-souscription".
 */
export interface PageSouscription {
  id: number;
  /**
   * Vide = « 100 ans ».
   */
  titre?: string | null;
  /**
   * Vide = « d’édition marxiste : ».
   */
  sousTitre?: string | null;
  /**
   * Vide = « aidez-nous à poursuivre l’histoire. ».
   */
  demande?: string | null;
  danger?: {
    /**
     * Vide = titre actuel.
     */
    titre?: string | null;
    /**
     * Optionnel, affichée en italique sous le titre. Vide = pas de 2ᵉ ligne (ou la 2ᵉ ligne actuelle).
     */
    titreItalique?: string | null;
    /**
     * Vide = texte actuel. Le gras est repris sur le site ; le souligné, lui, n’a AUCUN effet visuel sur le site (utilisez le gras à la place).
     */
    corps?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  guerre?: {
    /**
     * Vide = titre actuel.
     */
    titre?: string | null;
    /**
     * Optionnel, affichée en italique sous le titre. Vide = pas de 2ᵉ ligne (ou la 2ᵉ ligne actuelle).
     */
    titreItalique?: string | null;
    /**
     * Vide = texte actuel. Le gras est repris sur le site ; le souligné, lui, n’a AUCUN effet visuel sur le site (utilisez le gras à la place).
     */
    corps?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  maisons?: {
    /**
     * Vide = titre actuel.
     */
    titre?: string | null;
    /**
     * Optionnel, affichée en italique sous le titre. Vide = pas de 2ᵉ ligne (ou la 2ᵉ ligne actuelle).
     */
    titreItalique?: string | null;
    /**
     * Vide = texte actuel. Le gras est repris sur le site ; le souligné, lui, n’a AUCUN effet visuel sur le site (utilisez le gras à la place).
     */
    corps?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  appel?: {
    /**
     * Vide = titre actuel.
     */
    titre?: string | null;
    /**
     * Optionnel, affichée en italique sous le titre. Vide = pas de 2ᵉ ligne (ou la 2ᵉ ligne actuelle).
     */
    titreItalique?: string | null;
    /**
     * Vide = texte actuel. Le gras est repris sur le site ; le souligné, lui, n’a AUCUN effet visuel sur le site (utilisez le gras à la place).
     */
    corps?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Les montants et intitulés des trois paliers restent calés sur la jauge de collecte — seule la description qui les accompagne se modifie ici.
   */
  objectifs?: {
    /**
     * Vide = texte actuel.
     */
    descriptif50?: string | null;
    /**
     * Vide = texte actuel.
     */
    descriptif80?: string | null;
    /**
     * Vide = texte actuel.
     */
    descriptif100?: string | null;
  };
  /**
   * Aucune contrepartie = les neuf cartes actuelles. Montant et intitulé viennent du palier choisi — ils pilotent le paiement et ne s’éditent pas ici.
   */
  contreparties?:
    | {
        tierId:
          | 'palier-15'
          | 'palier-35'
          | 'palier-50'
          | 'palier-75'
          | 'palier-100'
          | 'palier-200'
          | 'palier-300'
          | 'palier-500'
          | 'palier-1000';
        /**
         * Une ligne par élément. Une ligne commençant par « ou » devient une alternative à la précédente (affichée « ou … », sans séparateur « + »).
         */
        items?:
          | {
              texte: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Pages légales, pied de page, réseaux sociaux et référencement. Un champ vide = texte actuel du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages-legales".
 */
export interface PagesLegales {
  id: number;
  /**
   * Remplace tout le corps de la page /cgv (chapeau compris) — le titre et le fil d’ariane restent fixes. Vide = texte actuel du site.
   */
  cgv?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Remplace tout le corps de la page /mentions-legales (chapeau compris). Vide = texte actuel du site (identité légale de l’éditeur).
   */
  mentionsLegales?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Remplace tout le corps de la page /confidentialite (chapeau compris). Vide = texte actuel du site.
   */
  confidentialite?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  footer?: {
    /**
     * Sous « Les Éditions sociales × La Dispute » (le nom reste fixe). Vide = texte actuel.
     */
    adresse?: string | null;
  };
  /**
   * Affichés dans le pied de page (cellule « Suivez-nous »). Aucun lien = pied de page inchangé.
   */
  reseauxSociaux?:
    | {
        label: string;
        /**
         * URL complète (https://…).
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Titre de la page d’accueil et suffixe des titres de pages (« Page — Titre »). Vide = titre actuel.
     */
    titreParDefaut?: string | null;
    /**
     * Méta-description par défaut du site. Vide = description actuelle.
     */
    descriptionParDefaut?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reglages-boutique_select".
 */
export interface ReglagesBoutiqueSelect<T extends boolean = true> {
  seuilAlerteStockBas?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-a-propos_select".
 */
export interface PageAProposSelect<T extends boolean = true> {
  heros?:
    | T
    | {
        titre?: T;
        intro?: T;
      };
  citation?:
    | T
    | {
        texte?: T;
        attribution?: T;
      };
  maisons?:
    | T
    | {
        maison?: T;
        nom?: T;
        tagline?: T;
        description?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        titre?: T;
        contenu?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-souscription_select".
 */
export interface PageSouscriptionSelect<T extends boolean = true> {
  titre?: T;
  sousTitre?: T;
  demande?: T;
  danger?:
    | T
    | {
        titre?: T;
        titreItalique?: T;
        corps?: T;
      };
  guerre?:
    | T
    | {
        titre?: T;
        titreItalique?: T;
        corps?: T;
      };
  maisons?:
    | T
    | {
        titre?: T;
        titreItalique?: T;
        corps?: T;
      };
  appel?:
    | T
    | {
        titre?: T;
        titreItalique?: T;
        corps?: T;
      };
  objectifs?:
    | T
    | {
        descriptif50?: T;
        descriptif80?: T;
        descriptif100?: T;
      };
  contreparties?:
    | T
    | {
        tierId?: T;
        items?:
          | T
          | {
              texte?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages-legales_select".
 */
export interface PagesLegalesSelect<T extends boolean = true> {
  cgv?: T;
  mentionsLegales?: T;
  confidentialite?: T;
  footer?:
    | T
    | {
        adresse?: T;
      };
  reseauxSociaux?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        titreParDefaut?: T;
        descriptionParDefaut?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}